cb: Fix strict aliasing warning
openocd fails to build with the default -Werror due to:

  src/target/riscv/riscv-013.c: In function \u2018write_memory_abstract\u2019:
  src/target/riscv/riscv-013.c:3153:6: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
        value = (*(uint32_t *)read_buffer & MASK16_LOW_BITS) | value;
        ^~~~~
  src/target/riscv/riscv-013.c:3157:6: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
        value = (*(uint32_t *)read_buffer & MASK8_LOW_BITS) | value;
        ^~~~~
  cc1: all warnings being treated as errors

Use buf_get_u32 to access read_buffer.